// src/config/iconConfig.js

import {
  HiMagnifyingGlass,
  HiOutlineBell,
  HiOutlineEye,
  HiOutlineUser,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineHome,
  HiOutlineNewspaper,
  HiOutlineLockClosed,
  HiXMark,
  HiChevronLeft,
  HiChevronRight,
  HiOutlineMagnifyingGlass,
  HiMiniPlusSmall,
  HiOutlineCog8Tooth,
  HiOutlineMoon,
  HiOutlineSun,
  HiOutlineDocumentText,
  HiOutlinePlus,
  HiOutlineRocketLaunch,
  HiOutlineTrophy,
  HiMiniChevronDown,
  HiMiniChevronUp,
  HiArrowDown,
  HiOutlineDocumentChartBar,
  HiOutlinePaperAirplane,
  HiPlus,
  HiOutlineCalendar,
  HiOutlineChevronDown,
} from "react-icons/hi2";
import { BiLoaderAlt } from "react-icons/bi";
import { CiFilter } from "react-icons/ci";
import { RiAttachmentLine, RiRobot2Line } from "react-icons/ri";
// Exporting all icons as a centralized object
export const icons = {
  HiOutlineEye,
  RiRobot2Line,
  HiOutlineCalendar,
  HiOutlineChevronDown,
  HiPlus,
  HiOutlineDocumentChartBar,
  HiOutlinePaperAirplane,
  HiArrowDown,
  RiAttachmentLine,
  HiOutlineRocketLaunch,
  HiMiniChevronDown,
  HiMiniChevronUp,
  HiOutlineTrophy,
  HiOutlineMoon,
  HiOutlineSun,
  HiOutlineDocumentText,
  HiOutlinePlus,
  CiFilter,
  HiMiniPlusSmall,
  HiOutlineCog8Tooth,
  BiLoaderAlt,
  HiXMark,
  HiOutlineMagnifyingGlass,
  HiChevronLeft,
  HiChevronRight,
  HiOutlinePencil,
  HiOutlineLockClosed,
  HiOutlineTrash,
  HiOutlineUser,
  HiMagnifyingGlass,
  HiOutlineHome,
  HiOutlineNewspaper,
  HiOutlineBell,
};

export type IconNames = keyof typeof icons;
